version: '3.7'

services:
  web:
    image: cws:latest
    command: ash -c "python manage.py migrate && python manage.py loaddata db_exclude_ct.json && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./cwsnew/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=den4e9
      - POSTGRES_DB=cws

volumes:
  postgres_data: