version: '3.7'

services:
  web:
    image: cws-prod:latest
    command: ash -c "python manage.py migrate && python manage.py loaddata db_exclude_ct.json && gunicorn cws.wsgi --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/static/
      - media_volume:/home/app/web/media/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    env_file:
      - ./.env.prod.db
  nginx:
    image: my_nginx:latest
    ports:
      - 1337:80
    environment:
      - STATIC_PATH=/home/app/web/static/
      - MEDIA_PATH=/home/app/web/media/
      - SERVER=web
      - PORT=8000
      - LISTEN_PORT=80
      - PROXY_PASS=http://cws

    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/static/
      - media_volume:/home/app/web/media/


volumes:
  postgres_data:
  static_volume:
  media_volume:
  