# Generated by Django 3.1.7 on 2021-10-14 07:02

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128, verbose_name='Тема')),
            ],
        ),
        migrations.CreateModel(
            name='ContentCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание карточки')),
                ('order', models.IntegerField(default=1000, verbose_name='Порядковый номер карточки')),
                ('label', models.CharField(default=models.IntegerField(default=1000, verbose_name='Порядковый номер карточки'), max_length=32, verbose_name='Обозначение карточки при пагинации')),
                ('topic', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='mainapp.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.topic', verbose_name='Тема')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='card_img/', verbose_name='Картинка карточки')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=512, verbose_name='Текст карточки')),
                ('order', models.IntegerField(default=1000, verbose_name='Порядковый номер карточки')),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.topic')),
            ],
        ),
    ]
