# Generated by Django 3.1.7 on 2021-05-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.topic'),
        ),
    ]
