# Generated by Django 3.1.7 on 2021-05-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionapp', '0004_questioncard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=512, verbose_name='Текст ответа'),
        ),
    ]
